metno/discovery-metadata-catalog-ingestor

- README.md
- codecov.yml
First PR to check GitHub Actions, integrations, etc.
> Additional Repo Setup

- .github/pull_request_template.md
- pyproject.toml
- tests/conftest.py
- tests/test_dummy.py
This PR adds a PR template and a basic pytest fixture to create a persistent temp folder for tests.
> Repo and Testing

- .github/workflows/pytest.yml
- dmci/__init__.py
- dmci/api/app.py
- dmci/config.py
- start_api.py
- tests/conftest.py
- tests/test_api/test_api.py
- tests/test_core/test_config.py
- tests/test_core/test_init.py
**Summary**:
Closes #11
Closes #5
> Finalise logging and code entry point

- .github/workflows/syntax.yml
- dmci/distributors/pycsw_dist.py
- external/py_mmd_tools/xml_utils.py
- requirements.txt
- setup.cfg
- tests/conftest.py
- tests/test_dist/test_pycsw_dist.py
**Summary**:
The PR:
* adds an `external/py_mmd_tools` folder with the files we need
* the dependencies for `dmci` have been updated and should now be complete and consistent between `requirements.txt` and `setup.cfg`
* the `pycsw_dist` code and tests have been updated to include the necessary docstrings
* the `pycsw_dist` tests have been given a significant rewrite to merge them into one test per function and instead use monkeypatch contexts to allow repeated mocking of the same objects
* the mockings have been simplified to use lambda functions to make the code simpler to read
* the name `id` was used multiple times as a variable name in the test file, but `id` is an intrinsic function, so the variable was renamed
The …
> Make py_mmd_tools work

- container/README.md
**Summary**:
Updated `README.md` for container.
None.
Any.
> updated readme

- container/Dockerfile
**Summary**:
Change to master branch temporary, until we have a minimum tag  version to use as base for the container.
None.
@mortenwh @vkbo 
> change to master mmd branch

- container/README.md
- container/config.yaml
**Summary**:
Update default config for container.
> update config for container

- container/Dockerfile
**Summary**:
updated container startup args
> updated container startup args

- dmci/api/app.py
- dmci/api/worker.py
- dmci/distributors/file_dist.py
- dmci/distributors/pycsw_dist.py
- tests/conftest.py
- tests/test_api/test_app.py
- tests/test_api/test_worker.py
- tests/test_dist/test_distributor.py
- tests/test_dist/test_file_dist.py
- tests/test_dist/test_pycsw_dist.py
**Summary**:
**Related issue**: #59 
> File and PyCSW distributor feedback

- dmci/api/app.py
- dmci/config.py
- example_config.yaml
- tests/conftest.py
- tests/test_api/test_app.py
- tests/test_core/test_config.py
**Summary**:
Add a rejected folder setting to config, and move all failed jobs there with an additional txt file with a dump of the error message.
Closes #46
> Issue #46: Rejected folder

- dmci/__init__.py
- dmci/api/app.py
- dmci/api/worker.py
- dmci/distributors/pycsw_dist.py
- tests/test_api/test_app.py
- tests/test_api/test_worker.py
- tests/test_dist/test_file_dist.py
- tests/test_dist/test_pycsw_dist.py
> Issue #74: PyCSW update and delete

- container/Dockerfile
**Summary**:
**Related issue**: closes #92 
> Issue92 dmci container

- container/Dockerfile
**Summary**:
**Related issue**: closes #85 
> Issue85 bug in dockerfile

- dmci/api/app.py
- dmci/api/worker.py
- dmci/config.py
- dmci/distributors/distributor.py
- dmci/distributors/pycsw_dist.py
- example_config.yaml
- tests/files/api/aqua-modis-parent.xml
- tests/files/mmd/mmd-to-geonorge.xslt
- tests/files/mmd/parent-uuid-list.xml
- tests/files/reference/parent_translated.xml
- tests/test_api/test_app.py
- tests/test_core/test_config.py
- tests/test_dist/test_distributor.py
- tests/test_dist/test_pycsw_dist.py
**Summary**:
Add parent uuid list file.
#90 
@johtoblan 
@mortenwh 
@ferrighi 
> issue90 parent child relationship

- container/Dockerfile
> Use MMD from branch issue_173 for testing

- .github/workflows/pytest.yml
- .github/workflows/syntax.yml
- setup.cfg
**Summary**: Support Python versions 3.6 ... 3.10 in the github pipeline
**Related issue**: closes #108 
**Suggested reviewer(s)**: mortenwh
> Issue108 support python versions

- dmci/api/worker.py
- tests/files/api/aqua-modis-parent.xml
- tests/files/api/failing.xml
- tests/files/api/passing.xml
- tests/files/mmd/parent-uuid-list.xml
- tests/files/reference/parent_translated.xml
- tests/files/reference/pycsw_dist_translated.xml
- tests/test_api/test_worker.py
> enforce namespace presence

- .gitlab-ci.yml
-moving .gitlab-ci.yml file to github repo.
-modified the file accordingly to run the pipeline from mirrored repo for dmci in gitlab
**Summary**:
> Add .gitlab-ci.yml file .

- .gitlab-ci.yml
-Replaced 'when:always' with 'when: on_success' in release job
**Summary**:
> Modified gitlab_ci.yml file

- .gitignore
- README.md
-Added more details about how to initialize config.yaml 
-Mentioned about 'mmd' repo.
**Summary**:
**Related issue**: #58
> Modify README.md

- Dockerfile
- README.md
- dmci/api/app.py
- dmci/api/worker.py
- dmci/config.py
- dmci/distributors/distributor.py
- dmci/distributors/file_dist.py
- dmci/distributors/pycsw_dist.py
- dmci/distributors/solr_dist.py
- example_config.yaml
- tests/conftest.py
- tests/test_dist/test_file_dist.py
- tests/test_dist/test_solr_dist.py
- tests/tools.py
> Issue165 test solrdist

- Dockerfile
> Added SSL netcdf fix for dmci container

- Dockerfile
- dmci/api/worker.py
- dmci/distributors/solr_dist.py
- tests/test_dist/test_solr_dist.py
> Fix cartopy

- dmci/distributors/solr_dist.py
- example_config.yaml
- tests/test_dist/test_solr_dist.py
**Summary**: Puts authentication initialization into its own function, and tests this in a test-function
**Related issue**: closes #173
> Test authentication only

- Dockerfile
> Fix issue 179

- dmci/distributors/solr_dist.py
> Changed comment to bump rebuild of container.

- requirements.txt
- setup.cfg
> Added solr-indexer version tag v2.0.0-senda

- dmci/distributors/pycsw_dist.py
> Fixed the update-function for pycsw update (#187)

- dmci/config.py
…Modify config.py such that solr username and password is read only from config.yaml
**Summary**:closes #170 
> Modify config.py 

- dmci/distributors/file_dist.py
> #201: added new method

- .github/workflows/pytest.yml
- dmci/__init__.py
- requirements.txt
- setup.cfg
> V0.2.8 solrindexer update - tag dmci as v0.2.8 when this PR is merged. Using latest solr-indexer v2.0.2-senda

- Dockerfile
**Summary**: set tag of MMD to 3.5.2 - this will solve the issues related to wrong wms urls. Unfortunately, there's quite a few other changes in MMD, so let's cross fingers....
> New version of MMD

- requirements.txt
- setup.cfg
> Bumped to master solrindexer for testing

- .gitlab-ci.yml
> Bump build, to update fixed version of solr-indexer

- requirements.txt
- setup.cfg
> Added new tagged solr-indexer version

- Dockerfile
**Summary**: expose port used for the flask metrics
> expose port 9200

- dmci/api/app.py
**Summary**: log only when relevant
> do not flood the logs with None strings

- dmci/api/worker.py
- dmci/distributors/pycsw_dist.py
- tests/files/reference/mmd_file.xml
- tests/test_dist/test_pycsw_dist.py
> Issue252 pycsw update
