metno/discovery-metadata-catalog-ingestor

- .github/workflows/pytest.yml
- tests/conftest.py
This may be more convenient for running tests against a pip install, but it also complicates running tests.
> Try a different way of running tests

- README.md
- dmci/api/README.md
- dmci/api/app.py
- requirements-dev.txt
- requirements.txt
- setup.cfg
**Summary**:
Making the class `App` a subclass of `Flask` simplifies a few things, so here it is.
The same PR also updates the main README.
Resolves #33 
> Issue #33: Make App a subclass of Flask

- README.md
**Summary**: Adds documentation how to send a file with curl to the insert endpoint
**Related issue**: Closes #45
**Suggested reviewer(s)**: @aheimsbakk 
> Add simple run-example in readme

- .github/workflows/pytest.yml
- dmci/distributors/pycsw_dist.py
- tests/test_dist/test_pycsw_dist.py
**Summary**:
* Drop the `xml.dom.minidom` import and instead use `lxml.etree` like everywhere else. This also properly handles namespaces, which minidom does not.
* Make the response parser and translate functions safer to use by adding exception handling.
* Extend tests
> XML fixes to dist_pycsw

- dmci/distributors/pycsw_dist.py
- tests/test_dist/test_pycsw_dist.py
**Summary**: I think this should close #62...
**Related issue**: #62
**Suggested reviewer(s)**: @vkbo @aheimsbakk @TAlonglong 
> #62: conversion from bytes to string object should solve the issue..

- dmci/distributors/pycsw_dist.py
- tests/test_dist/test_pycsw_dist.py
> Make the xml translator work in bytes only

- .github/workflows/pytest.yml
- dmci/api/worker.py
- dmci/mmd_tools/check_mmd.py
- tests/test_api/test_worker.py
- tests/test_mmd_tools/test_mmd_tools.py
**Summary**:
This is a rewrite of the `check_urls` function. It now only checks that the url is ASCII, contains one of the following schemes: http, https, ftp, sftp, and checks that it has a domain with at least one dot.
The `full_check` is now enabled again, with the rectangle and url checks, and the vocabulary checks disabled for now.
Part of #49, closes #68
> Rewrite check_urls

- dmci/distributors/file_dist.py
- tests/test_dist/test_file_dist.py
**Summary**:
This PR adds the code for the delete command in file_dist, and changes the insert/update command to fail when the user tries to insert when a file exists, or update when a file does not exist. These serve as a low level safe guard for an erroneous call to the API.
Colses #57
> Issue #57: Implement update and delete in file_dist

- dmci/api/app.py
- tests/test_api/test_app.py
**Summary**:
This PR correctly fixes the line endings problem for API return messages.
Closes #79, replaces PR #81
> Issue #79: API return message line endings

- dmci/api/app.py
- dmci/api/worker.py
- tests/test_api/test_app.py
- tests/test_api/test_worker.py
**Summary**:
This PR adds a `/vi/validate` endpoint to the API that will validate a single file without calling any distributors.
Closes #78
> Issue #78: Add validator command to API

- README.md
- dmci/api/app.py
- dmci/api/worker.py
- dmci/distributors/distributor.py
- dmci/distributors/file_dist.py
- tests/conftest.py
- tests/test_dist/test_distributor.py
- tests/test_dist/test_file_dist.py
- tests/test_dist/test_pycsw_dist.py
**Summary**:
- Adds alias for insert command: create
- Updates readme to add this
- Fixes an issue with keyword argument dictionary being unpacked causing multiple instances of some keywords
- Delete_from_archive in file_distributor does not use uninstanced _file_metadata_id
- Enforce metadata_id to be of type UUID 
Closes #87 
Partly? Closes #88 
@mortenwh 
> Issue87 file archive delete fix

- tests/files/mmd/mmd-to-geonorge.xslt
- tests/files/mmd/mmd.xsd
- tests/files/reference/pycsw_dist_translated.xml
**Summary**:
Updates MMD-files used in testing to MMD [v3.3](https://github.com/metno/mmd/releases/tag/v3.3)
Used xsltproc to translate /tests/files/passing.xml to /tests/files/referemce/pycsw_dist_translated.xml
Tested with and without file_name without crashing.
Closes #91 
@mortenwh 
> Check if mmd v3.3 can be imported

- container/Dockerfile
**Summary**:
Dockerfile uses tagged version of MMD, to not build unready versions of dmci.
> Use tagged version of MMD

- .github/workflows/pytest.yml
- .github/workflows/syntax.yml
**Summary**: Updates github actions to new node.js versions and python test to test versions 3.7 - 3.11
**Related issue**: Closes #114
> Add python 3.11 to tests, update github actions

- dmci/api/worker.py
- tests/test_api/test_worker.py
**Summary**:
Changes local types of fileUUID and namespace to str, to check edge case where namespace or fileUUID resolved to \"\". (Cases where metadata_identifier is either ":", "VALIDNS:" or ":VALIDUUID"
Also extended testing of missing namespace
Returns test-coverage to 100%
> Get back to 100% test coverage

- dmci/api/worker.py
- tests/test_api/test_worker.py
(since catalog_url in the kubernetes config is e.g. "https://data.met.no/" not "https://data.met.no/dataset")
fixes #182 
**Summary**:
> add /dataset/ in the landing page path 

- dmci/distributors/distributor.py
- dmci/distributors/solr_dist.py
- tests/test_dist/test_pycsw_dist.py
- tests/test_dist/test_solr_dist.py
**Summary**: 
- Fixes an error in SolrDistribute, where it will get multiple metadata_UUID, due to positional and keyword arguments
- Fixes enforcing of namespace on the construct-identifier-function for the worker-class.
- Rewrote tests for SolrDistribute.delete functionality
> Change metadata_id to UUID in solrDist

- dmci/__init__.py
- requirements.txt
- tests/test_core/test_init.py
**Summary**: extract metrics via prometheus_flask_exporter
#220
> add prometheus_flask_exporter

- setup.cfg
**Summary**:  #233 was missing a dependency in setup.cfg
> dependency needs to be added to setup.cfg too

- Dockerfile
- container/gunicorn_promexp_config.py
- container/wsgi.py
**Summary**: use GunicornPrometheusMetrics
**Related issue**: #220
> use GunicornPrometheusMetrics

- container/wsgi.py
- dmci/api/app.py
- tests/test_api/test_app.py
**Summary**: define custom metrics to be collected together with the standard ones from the prometheus-flask-exporter
> Custom metrics

- container/wsgi.py
**Summary**: I think that the extra CollectorRegistry() broke the metrics, the standard flask collector does not work anymore at the moment https://dmci.s-enda-dev.k8s.met.no/metrics, so trying to remove it. testing with a local container still exposes everything so hard to tell if this will fix..
**Related issue**: #220
> remove collector registry

- Dockerfile
- container/gunicorn_prometheus_config.py
- container/wsgi.py
**Summary**: this again for me exposes all the metrics at port 9200 when I run the container with docker....
> back to GunicornPrometheusMetrics, CollectorRegistry, port 9200

- dmci/api/app.py
- tests/test_api/test_app.py
**Summary**: the string returned in case pycsw distributor fails was wrong
> fix string name

- dmci/api/app.py
- tests/test_api/test_app.py
**Summary**:
if there is no env_string we still need to check that the namespace does not contain a .dev or .staging, as it could be as a result of a mistake so far not prevented at the point of ingestion
**Related issue**: 
#229
> Namespace checks

- tests/test_dist/test_pycsw_dist.py
> #247: use fixture

- dmci/distributors/pycsw_dist.py
- tests/test_dist/test_pycsw_dist.py
> Issue236 update

- dmci/api/worker.py
- tests/files/api/staging.xml
- tests/test_api/test_worker.py
**Summary**: if the namespace already contains a string mismatched with the env string, file should be rejected
#228 
> reject if namespace contains string mismatched with env

- container/wsgi.py
**Summary**: trying to address `ValueError: Duplicated timeseries in CollectorRegistry` 
**Related issue**: #255 
> try fix CollectorRegistry issue
